version: '3.9'

networks:
  traefik-public:
    external: true
    name: ${PROJECT}_traefik-public
  cms:
    external: true
    name: ${PROJECT}_cms
  metrics:
    external: true
    name: ${PROJECT}_metrics
  socat:
    external: true
    name: ${PROJECT}_socat

volumes:
  mariadb_data:
    name: ${PROJECT}_wordpress_mariadb
    driver: local
  wordpress_html_data:
    name: ${PROJECT}_wordpress_html
    driver: local
  prometheus:
    name: ${PROJECT}_prometheus
    driver: local
  grafana:
    name: ${PROJECT}_grafana
    driver: local
  loki-data:
    name: ${PROJECT}_loki
    driver: local
