version: '3.9'

networks:
  traefik-public:
    external: true
    name: ${PROJECT}_traefik-public
  socat:
    external: true
    name: ${PROJECT}_socat

volumes:
  elastic_data:
    driver: local
    name: ${PROJECT}_elastic_efk

services:
  docker-api-socat:
    image: tecnativa/docker-socket-proxy:0.1
    networks:
      - socat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      # SWARM: 1
      TASKS: 1
    logging:
      driver: none
    deploy:
      mode: global
      placement:
        constraints: [ node.role == manager ]

  ### reverse-proxy
  reverse-proxy:
    #    <<: *default-opts
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: traefik.logs
    image: traefik:v2.9
    depends_on:
      - docker-api-socat
    command:
      - --api.dashboard=true
      #      - --log.level=INFO
      - --log.format=json
      #      - --log.filePath=/logs/traefik.log
      - --accessLog=true
      - --accesslog.format=json
      #      - --accesslog.filters.statuscodes=200,300-302,404,500
      #      - --accesslog.filters.retryattempts
      - --accesslog.format=json
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.names.User-Agent=redact
      - --accesslog.fields.headers.names.Authorization=drop
      - --accesslog.fields.headers.names.Content-Type=keep
      #      - --accesslog.filters.minduration=10
      #      - --accesslog.filepath=/logs/access.log
      - --providers.docker=false
      #      - --providers.file.directory=/custom/
      #      - --providers.file.watch
      - --entrypoints.web.address=:80
      #      - --entrypoints.websecure.address=:443
      #      - --entrypoints.websecure.http.tls=true
      #      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      #      - --entrypoints.web.http.redirections.entrypoint.priority=1000
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-api-socat:2375
#      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.swarmMode
      - --providers.docker.network=${PROJECT}_traefik-public
      - --providers.docker.watch
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
    networks:
      traefik-public:
        aliases:
          - traefik
      socat:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    #      - target: 443
    #        published: 443
    #        protocol: tcp
    #        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: false
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      labels:
        - traefik.enable=true
        - traefik.http.routers.${PROJECT}_dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        - traefik.http.routers.${PROJECT}_dashboard.service=api@internal
        - traefik.http.services.${PROJECT}_dummy-svc.loadbalancer.server.port=9999
        - traefik.http.routers.${PROJECT}_dashboard.entrypoints=web