global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - /alert.rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox-self'
    metrics_path: '/blackbox/metrics'
    static_configs:
      - targets: ['blackbox:9115']

  - job_name: 'blackbox'
    metrics_path: '/blackbox/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://cms.example.com
        - http://cms.example.com/database
        - http://cms.example.com/grafana
        - http://cms.example.com/prometheus
        - http://cms.example.com/alertmanager
        - http://cms.example.com/dashboard/#/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'blackbox_tcp'
    metrics_path: '/blackbox/probe'
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - nginx:80
        - docker-api-socat:2375
        - cadvisor:8080
        - database:3306
        - grafana:3000
        - loki:3100
        - mysql_exporter:9104
        - node_exporter:9100
        - pma:8081
        - reverse-proxy:80
        - wordpress:9000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: traefik
    static_configs:
      - targets: [ 'traefik:8082' ]
        labels:
          alias: reverse-proxy

  - job_name: 'common'
    docker_sd_configs:
      - host: tcp://docker-api-socat:2375
    relabel_configs:
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [ __meta_docker_container_label_prometheus_job ]
        regex: .+
        action: keep
      # Only with prometheus network
      - source_labels: [ __meta_docker_network_name ]
        regex: metrics
        action: keep
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1

alerting:
  alertmanagers:
    - path_prefix: '/alertmanager'
      static_configs:
        - targets:
            - alertmanager:9093