global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: traefik
    static_configs:
      - targets: [ 'traefik:8082' ]
        labels:
          alias: reverse-proxy

  - job_name: 'common'
    docker_sd_configs:
      - host: tcp://docker-api-socat:2375
    relabel_configs:
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [ __meta_docker_container_label_prometheus_job ]
        regex: .+
        action: keep
      # Only with prometheus network
      - source_labels: [ __meta_docker_network_name ]
        regex: metrics
        action: keep
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1